//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the OData model generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace EdmGraph.Syn;

#region child  element interfaces

/// <summary>
/// interface for all children of Model.
/// implemented by <see cref="Schema"/>.
/// </summary>
public interface IModelChild : INode { }

/// <summary>
/// interface for all children of Schema.
/// implemented by <see cref="EnumType"/>, <see cref="ComplexType"/>, <see cref="PrimitiveType"/>, <see cref="Term"/>.
/// </summary>
public interface ISchemaChild : INode { }

/// <summary>
/// interface for all children of EnumType.
/// implemented by <see cref="Member"/>, <see cref="Annotation"/>.
/// </summary>
public interface IEnumTypeChild : INode { }

/// <summary>
/// interface for all children of Member.
/// implemented by <see cref="Annotation"/>.
/// </summary>
public interface IMemberChild : INode { }

/// <summary>
/// interface for all children of ComplexType.
/// implemented by <see cref="Property"/>, <see cref="Annotation"/>.
/// </summary>
public interface IComplexTypeChild : INode { }

/// <summary>
/// interface for all children of Property.
/// implemented by <see cref="Annotation"/>.
/// </summary>
public interface IPropertyChild : INode { }

/// <summary>
/// interface for all children of PrimitiveType.
/// implemented by <see cref="Annotation"/>.
/// </summary>
public interface IPrimitiveTypeChild : INode { }

/// <summary>
/// interface for all children of Annotation.
/// implemented by <see cref="Annotation"/>.
/// </summary>
public interface IAnnotationChild : INode { }

/// <summary>
/// interface for all children of Term.
/// implemented by <see cref="Annotation"/>.
/// </summary>
public interface ITermChild : INode { }
#endregion child  element interfaces

/// <summary>
/// Interface for model elements that can be referenced by Property.Type
/// Implemented by PrimitiveType, ComplexType, EnumType
/// </summary>
public interface IPropertyType : INode { }

/// <summary>
/// Interface for model elements that can be referenced by Term.Type
/// Implemented by PrimitiveType, ComplexType
/// </summary>
public interface ITermType : INode { }

public class Model : INode
{
    public Model() => Children = new(this);

    public ChildElementCollection<IModelChild> Children { get; }

    IEnumerable<INode> INode.Children => Children;

    INode? INode.Parent { get; set; }

    Sem.INode INode.Prepare()
    {
        return new Sem.Model
        {
        };
    }
}

public class Schema : INode, IModelChild
{
    public Schema() => Children = new(this);

    public ChildElementCollection<ISchemaChild> Children { get; }

    IEnumerable<INode> INode.Children => Children;

    INode? INode.Parent { get; set; }

    public required string Namespace { get; init; }

    public string? Alias { get; init; }

    Sem.INode INode.Prepare()
    {
        return new Sem.Schema
        {
            Namespace = Namespace,
            Alias = Alias,
        };
    }
}

public class EnumType : INode, ISchemaChild
{
    public EnumType() => Children = new(this);

    public ChildElementCollection<IEnumTypeChild> Children { get; }

    IEnumerable<INode> INode.Children => Children;

    INode? INode.Parent { get; set; }

    public required string Name { get; init; }

    public required bool IsFlags { get; init; }

    public UnderlyingType? UnderlyingType { get; init; }

    Sem.INode INode.Prepare()
    {
        return new Sem.EnumType
        {
            Name = Name,
            IsFlags = IsFlags,
            UnderlyingType = UnderlyingType,
        };
    }
}

public class Member : INode, IEnumTypeChild
{
    public Member() => Children = new(this);

    public ChildElementCollection<IMemberChild> Children { get; }

    IEnumerable<INode> INode.Children => Children;

    INode? INode.Parent { get; set; }

    public required string Name { get; init; }

    public int? Value { get; init; }

    Sem.INode INode.Prepare()
    {
        return new Sem.Member
        {
            Name = Name,
            Value = Value,
        };
    }
}

public class ComplexType : INode, ISchemaChild
{
    public ComplexType() => Children = new(this);

    public ChildElementCollection<IComplexTypeChild> Children { get; }

    IEnumerable<INode> INode.Children => Children;

    INode? INode.Parent { get; set; }

    public required string Name { get; init; }

    public bool? Abstract { get; init; }

    // the name of a ComplexType node
    public string? BaseType { get; init; } = default!; // set via UpdateReferences

    Sem.INode INode.Prepare()
    {
        return new Sem.ComplexType
        {
            Name = Name,
            Abstract = Abstract,
        };
    }
}

public class Property : INode, IComplexTypeChild
{
    public Property() => Children = new(this);

    public ChildElementCollection<IPropertyChild> Children { get; }

    IEnumerable<INode> INode.Children => Children;

    INode? INode.Parent { get; set; }

    public required string Name { get; init; }

    // the name of a PrimitiveType, ComplexType or EnumType node
    public required string Type { get; init; }

    public bool? Nullable { get; init; }

    public string? DefaultValue { get; init; }

    public bool? IsCollection { get; init; }

    Sem.INode INode.Prepare()
    {
        return new Sem.Property
        {
            Name = Name,
            Nullable = Nullable,
            DefaultValue = DefaultValue,
            IsCollection = IsCollection,
        };
    }
}

public class PrimitiveType : INode, ISchemaChild
{
    public PrimitiveType() => Children = new(this);

    public ChildElementCollection<IPrimitiveTypeChild> Children { get; }

    IEnumerable<INode> INode.Children => Children;

    INode? INode.Parent { get; set; }

    public required string Name { get; init; }

    Sem.INode INode.Prepare()
    {
        return new Sem.PrimitiveType
        {
            Name = Name,
        };
    }
}

public class Annotation : INode, IEnumTypeChild, IMemberChild, IComplexTypeChild, IPropertyChild, IPrimitiveTypeChild, IAnnotationChild, ITermChild
{
    public Annotation() => Children = new(this);

    public ChildElementCollection<IAnnotationChild> Children { get; }

    IEnumerable<INode> INode.Children => Children;

    INode? INode.Parent { get; set; }

    // the name of a Term node
    public required string Term { get; init; }

    Sem.INode INode.Prepare()
    {
        return new Sem.Annotation
        {
        };
    }
}

public class Term : INode, ISchemaChild
{
    public Term() => Children = new(this);

    public ChildElementCollection<ITermChild> Children { get; }

    IEnumerable<INode> INode.Children => Children;

    INode? INode.Parent { get; set; }

    public required string Name { get; init; }

    // the name of a PrimitiveType or ComplexType node
    public required string Type { get; init; }

    public string? Qualifier { get; init; }

    public required AppliesTo AppliesTo { get; init; }

    Sem.INode INode.Prepare()
    {
        return new Sem.Term
        {
            Name = Name,
            Qualifier = Qualifier,
            AppliesTo = AppliesTo,
        };
    }
}
